# Generated by Django 6.1 on 2026-08-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_nonce',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='encrypted_diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
    ]
