# Generated by Django 6.1 on 2026-08-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_doctorkey_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
