# Generated by Django 6.1 on 2026-08-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_medicalrecord_diagnosis_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='prev_hash',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
