# Generated by Django 6.1 on 2026-08-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_medicalrecord_prev_hash_medicalrecord_record_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diagnosis',
        ),
    ]
